### ISSUE TITLE
Emmet in editor (HTML + JS)

### ISSUE THREAD

**Issue by JWo1F** [voronianski/esnextbin#13]
Hi all! @voronianski, thank you for this project!
I want to use the one, but it doesn't support Emmet. It's very-very sadly. Can someone do it?

**Comment by voronianski** [comment]
@JWo1F thanks! I think it's possible, stay tuned! :+1:

**Comment by JWo1F** [comment]
@voronianski wow! Cool :)
Thx. I'll wait.

**Comment by minwe** [comment]
Maybe like this:

```javascript
import React from 'react';
import { render } from 'react-dom';
import brace from 'brace';
import AceEditor from 'react-ace';

import 'brace/mode/html';
import 'brace/theme/github';

// import emmet extension
import 'brace/ext/emmet';

function onChange(newValue) {
  console.log('change',newValue);
}

// Render editor
render(
  <AceEditor
    mode="html"
    theme="github"
    onChange={onChange}
    name="UNIQUE_ID_OF_DIV"
    editorProps={{$blockScrolling: true}}
    {/* set option */}
   setOptions={{enableEmmet: true}}
  />,
  document.getElementById('example')
);
```

via https://github.com/ajaxorg/ace/blob/master/demo/emmet.html#L26-L40

```
https://cloud9ide.github.io/emmet-core/emmet.js
```

The emmet script is also needed.

**Comment by voronianski** [comment]
added emmet support in latest version (via https://github.com/voronianski/esnextbin/commit/3622a867c1f5be89e814141e585838a84ca9034e).
