### ISSUE TITLE
Importing the package to project

### ISSUE THREAD

**Issue by roshanpshajan** [voronianski/esnextbin#15]
How do I import and use this package within my React project, after doing the 'npm install esnextbin'? I couldn't see a proper documentation on how to set up this library in my project. (P.S: I am fairly new to the software industry, forgive me if this query is really dumb.)

**Comment by voronianski** [comment]
@roshanpshajan actually what you can is to insert `index.html` into your app's `<iframe />` or use some of the [pure components](https://github.com/voronianski/esnextbin/tree/master/src/components) inside of your React app.
