### ISSUE TITLE
Add 'allow-same-origin' to sandbox property of iframe

### ISSUE THREAD

**Issue by gunar** [voronianski/esnextbin#16]
Hi and thanks for esnextbin!

Could you please add `allow-same-origin` to the sandbox property of the iframe?
Without it I can't use `URL.createObjectURL` because it returns e.g. `blob:null/0a03b0a9-4115-4f30-bbeb-eeaae6c0d2ff` and that doesn't work.

> Blob urls are subject to an origin policy. This means that they can only be used in documents that have the same site-of-origin as the document running the script that created the url. If you need to use the blob object from an \<iframe> that is running in a different domain, you must use the postMessage API to send the blob data to the frame and then create the blob: url there. [Source](https://msdn.microsoft.com/en-us/library/windows/apps/hh453196.aspx)

**Comment by voronianski** [comment]
@gunar I'm not sure this will be safe decision (http://stackoverflow.com/a/35208356/2117550)

**Comment by gunar** [comment]
Hm.. Yeah I don't know where that might lead us. Still, [jsfiddle](http://jsfiddle.net) has it :P

**Comment by voronianski** [comment]
@gunar I've added support for it, enjoy :)

**Comment by gunar** [comment]
@voronianski you're awesome. thanks!
