### ISSUE TITLE
can't save gist/private gist

### ISSUE THREAD

**Issue by odyright** [voronianski/esnextbin#162]

**Comment by ffxsam** [comment]
Way hosed.

**Comment by jameswomack** [comment]
Same as #165 I believe. Maybe we can fork this and deploy it elsewhere on Heroku as a temporary fix. I remember when I worked on the "Enable Autorun" feature that I had it deployed on Heoku somewhere and it seemed to work well.

**Comment by voronianski** [comment]
issue fixed
