### ISSUE TITLE
NPM packages not supported

### ISSUE THREAD

**Issue by andrewkmin** [voronianski/esnextbin#163]
For some reason, the NPM packages `moment` and `moment-business-days` don't seem to work here. I'm including them in my package.json - equivalent: `{
  "name": "esnextbin-sketch",
  "version": "0.0.0",
  "dependencies": {
    "babel-runtime": "6.25.0",
    "async": "2.5.0",
    "moment": "2.18.1",
    "moment-business-days": "1.0.6"
  }
}`
Additionally, I'm requiring it in a pretty standard way: `var moment = require('moment-business-days');`
Please advise. Not sure why, but I'm getting the following error:
```npm ERR! Cannot read property 'moment' of undefined```

Thanks!

**Comment by voronianski** [comment]
This is due to how [browserify-cdn](https://wzrd.in) works (every module gets browserfied on its' own) and `'moment-business-days'` having `moment` as `peerDependency` (they are not installed by default `npm i` command).
