### ISSUE TITLE
Github Authorization is broken

### ISSUE THREAD

**Issue by n1ru4l** [voronianski/esnextbin#165]
I am not able to authorize the app to github in order to save my code as a pen. After authorizing I am stuck in a loop. 

![login-is-broken](https://user-images.githubusercontent.com/14338007/32160413-fa8e8dc8-bd51-11e7-9150-1c55b9547c67.gif)

**Comment by jameswomack** [comment]
@voronianski  I have the same issue. It's a CORS thing. 

```
Cross-Origin Request Blocked: The Same Origin Policy 
disallows reading the remote resource at 
https://labs.voronianski.com/gatekeeper/token.php?code=setImmediate%240.8135372327491078%2417. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by voronianski** [comment]
should be fixed with next redeploy today
