### ISSUE TITLE
moving back to wzrd.in

### ISSUE THREAD

**Issue by goto-bus-stop** [voronianski/esnextbin#168]
wzrd.in is now hosted on a new server for bandwidth cost reasons, so I'd like to take wzrd.now.sh down soon. i'll keep it up as long as esnextb.in is still using it tho :)

(hopefully wzrd.in will be more stable now for real, unfortunately someone was using it in their official Android SDK which caused essentially a months-long DDOS taking the server down every few hours. i've contacted them about it, we'll see…)

**Comment by voronianski** [comment]
@goto-bus-stop thanks, sounds promising! can I already replace `wzrd.now.sh` with `wzrd.in`?

**Comment by goto-bus-stop** [comment]
Yes, I set up CloudFlare to block the the DDOS-y requests so the load is bearable now.

**Comment by goto-bus-stop** [comment]
Hmm actually no, wait a while, there's still some fun times going on. I need to tweak the server config a bit more. I'll let you know when it's ready!

**Comment by voronianski** [comment]
@goto-bus-stop will do today, ping me if it's dangerous to do this again :)

**Comment by voronianski** [comment]
live now

**Comment by voronianski** [comment]
@goto-bus-stop not sure if you're still maintaining wzrd.in but this issue breaks esnextb.in - https://github.com/browserify/wzrd.in/issues/198

**Comment by voronianski** [comment]
returned back to https://wzrd.now.sh
