### ISSUE TITLE
React native support ?

### ISSUE THREAD

**Issue by bogas04** [voronianski/esnextbin#17]
The tool is fantastic ! I am literally prototyping my work on ESNextBin and even recommending it to people who want to learn React and ES2015. 

React Native on other hand faces similar tooling issue and hence has a lot of fatigue in some sense. Can something like [rnplay.org](https://rnplay.org/) be integrated into ESNextBin ? Surely a long-shot, though!

**Comment by voronianski** [comment]
@bogas04 I'm not sure that this should be done inside of esnextbin as it will overcomplicate it a lot. Probably there's a reason to create somekind of similar service but as react-native playground however as I am not in react-native development right now I won't start it for now.
