### ISSUE TITLE
CPU intensive hanging

### ISSUE THREAD

**Issue by gaving** [voronianski/esnextbin#18]
Hey there, I'm having a bit of an issue with esnextbin crashing chrome.

Cloned the repo, then:-

`npm install && npm run build && npm run start`

Launched http://localhost:9292

Pacman logo appears then chrome just goes unresponsive.

Tried to track it down but got a bit lost, appears the 

`onCodeChange={::this.handleCodeChange}`

handler in the `render()` function within Main.jsx is hitting an infinite loop when triggered by the `setState()` change within `handleCodeChange()`.

Had a look at https://github.com/facebook/react/issues/5591 and tried a `process.nextTick()` workaround to no avail.

Any ideas?

**Comment by voronianski** [comment]
@gaving sorry, I've never run `npm install && npm run build && npm run start` simultaneously.

**Comment by gaving** [comment]
@voronianski Confused, running them simultaneously or not shouldn't matter?

So you can't recreate this? Just tried again with a fresh clone, instant Chrome hang 100% CPU.

**Comment by voronianski** [comment]
@gaving could you try with latest `master`?

**Comment by gaving** [comment]
@voronianski Woah, that seems to have sorted it! 👍 

I guess there was some sort of bug in one of the dependencies?

Drove me nuts debugging this and trying to come up with a solution, I ended up giving up. 😵
