### ISSUE TITLE
Make it embeddable in Medium

### ISSUE THREAD

**Issue by gsklee** [voronianski/esnextbin#19]
So we can embed it properly inside Medium, tumblr, etc... 😄

**Comment by voronianski** [comment]
@gsklee I would like to think about it :)

**Comment by gsklee** [comment]
Okay so, firstly, I've updated the issue to specifically target Medium, where I'd really like to see it work...

And it's way trickier than I thought. [Medium is using a 3rd-party service](https://help.medium.com/hc/en-us/articles/214981378-Embeds) called Embedly to handle embedded content, and Embedly has [a long list of requirements](http://embed.ly/providers/new) a content provider must fulfill before an application can be submitted to Embedly, which will then get into contact with us to facilitate the actual integration process.

Some highlights amongst the requirements are: HTTPS is a must, and iframe embed is a must too.

**Comment by voronianski** [comment]
@gsklee nice! thanks! I will proceed with it
