### ISSUE TITLE
Feature Request: Revision in the URL

### ISSUE THREAD

**Issue by kentcdodds** [voronianski/esnextbin#2]
Would be really nice to be able to reference an older revision of the gist via the URL. Something like:

```
http://esnextb.in/?gist=27fd38f51a4a9303e9c7&revision=1
```

Or something like that :+1:

**Comment by voronianski** [comment]
@kentcdodds thanks!

**Comment by voronianski** [comment]
@kentcdodds added support for revisions, though gist API only support sha of revision not its' number, example http://esnextb.in/?gist=6764988861c8171d982b&sha=945f1547fbd8f9ac96f1e593521a0c9f09b6c9f7

Use `rev` or `sha` query param.

**Comment by kentcdodds** [comment]
That's reasonable. Thanks!
