### ISSUE TITLE
Make embeddable display easier to view at smaller widths

### ISSUE THREAD

**Issue by jameshibbard** [voronianski/esnextbin#21]
Hey,

We're experimenting with embedding ESNextbin using an iframe and in itself, this works pretty well ([demo](http://www.sitepoint.com/?p=130124&preview=1&_ppp=537926d229)).

However, AFAICT the _Code_ pane and the _HTML Preview_ pane always appear side by side. This means that at smaller widths you get a horizontal scrollbar on the embed which makes the code hard to read. 

Would it be possible to have the _HTML Preview_ appear beneath the _Code_ view? Or alternatively, would it be possible to have the _HTML Preview_ as a separate pane which you can toggle between (a little like a CodePen embed's _Result_ tab)?

Thanks for a great app.

**Comment by voronianski** [comment]
@jameshibbard hey! demo looks cool! Potentially this is possible and I have some plans to do it in scope of this issue - https://github.com/voronianski/esnextbin/issues/19

**Comment by jameshibbard** [comment]
We just moved everything to https, so the demo broke :(
Any plans to serve esnextb.in over https?

**Comment by voronianski** [comment]
@jameshibbard here is an issue for this - https://github.com/voronianski/esnextbin/issues/20 

I plan to look at it as soon as I have more free time, probably this weekend.

**Comment by voronianski** [comment]
@jameshibbard https://esnextb.in is served via `https` now :) Now your demo looks like:

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202016-06-18%20%D0%B2%2023.14.01.png)

Now I'm thinking on updates for smaller widths. Maybe it's really necessary to add "Preview" button to header and make it possible to turn it on/off.

Also I'm thinking of removing "Actions" button from small widths, especially when it's embeddable there's no need in all these actions.

**Comment by jameshibbard** [comment]
> Now I'm thinking on updates for smaller widths. Maybe it's really necessary to add "Preview" button to header and make it possible to turn it on/off.

That would be great. If you do that, would it be possible to specify which panes to have open when you embed it? In our case it would be great if the embed initially showed with just the preview, but readers had the chance to toggle the other views (Code, HTML, Package).

> Also I'm thinking of removing "Actions" button from small widths, especially when it's embeddable there's no need in all these actions.

Yeah, that makes sense.

**Comment by gsklee** [comment]
+1

In my case I'd like to initially show the Code view, but allow readers the ability to switch to the HTML view or the (not yet implemented) Console view.

**Comment by voronianski** [comment]
@jameshibbard @gsklee what do you think, should it be just representation of the sketch's code and result without possibility to edit it inside embed view?

**Comment by gsklee** [comment]
@voronianski I think it's a reasonable way to simplify the embedded view. Just add an "Edit" button which when clicked will open the code in esnextbin's main site.

**Comment by jameshibbard** [comment]
If that makes life simpler, it works for us.

**Comment by voronianski** [comment]
https://esnextb.in now supports mobile screens, so it also can be embedded with smaller width on the websites. It contains all actions and buttons. 

However I still plan to work on special embed view (e.g. https://esnextb.in/embed`) in order to be able to just display the code (and maybe console) without editing functionality.
