### ISSUE TITLE
Save Gist is not working

### ISSUE THREAD

**Issue by gsklee** [voronianski/esnextbin#26]
Saving to public/private Gist is currently not working it seems.

**Comment by voronianski** [comment]
@gsklee thanks, working on it!

**Comment by voronianski** [comment]
@gsklee fixed!

**Comment by odyright** [comment]
Hello @voronianski i'm facing the same issue!

**Comment by salmaanahmed** [comment]
@voronianski seems like issue has occurred again. Its not saving :(
