### ISSUE TITLE
Feature Request: Autorun

### ISSUE THREAD

**Issue by kentcdodds** [voronianski/esnextbin#3]
I'm sure you've already thought about this. Just putting it in the issue tracker. I'd think something like a debounce of 500ms or less.

**Comment by voronianski** [comment]
@kentcdodds yeah, I was thinking about that (however I decided that it's a bit tricky for first release).

**Comment by kentcdodds** [comment]
:+1: way to not let that hold up your release :D

**Comment by voronianski** [comment]
@kentcdodds released, you can enable Autorun feature in `Actions` menu.
