### ISSUE TITLE
Support for Scoped packages 

### ISSUE THREAD

**Issue by real34** [voronianski/esnextbin#4]
When adding the following import, and clicking on "Execute" the UI stays stalled and nothing is rendered:

```
import Cycle from '@cycle/core';
```

Expected: Cycle should be available in the page, and added to the packages tab

**Comment by voronianski** [comment]
@real34 it's a problem with [browserify-cdn](https://wzrd.in/standalone/@cycle%2Fcore@latest) or (most likely) `@cycle/core` package itself. I'll try to investigate it today.

**Comment by voronianski** [comment]
@real34 it's an npm bug - https://github.com/npm/npm/issues/6581#issuecomment-174718361

Create PR to cycle-core repo - https://github.com/cyclejs/cycle-core/pull/207

**Comment by voronianski** [comment]
@real34 please check, it should work now.

**Comment by real34** [comment]
Awesome, it works fine with `@cycle/core`! Thank you for pointing to these different issues. I'll send PR for other related projets

**Comment by voronianski** [comment]
@real34 cool, you can share the link with your bin with `@cycle/core` and I'll add it to demos section - https://github.com/voronianski/esnextbin#demos :)

**Comment by real34** [comment]
@voronianski not working yet because there is another issue with `@cycle/dom` I'd have to debug.
See https://wzrd.in/standalone/@cycle%2Fdom@latest

FYI the sample code I have is:

```
import {run} from '@cycle/core';
// FIXME import {makeDOMDriver, div, h1, span} from '@cycle/dom';

function main ({DOM}) {
	const clicks$ = DOM.select(':root').events('click')
  	.scan(total => total+1, 0)
    .startWith(0);
  
  return {
    DOM: clicks$.map(clicks => div([
      h1('Hi!'),
      span(`You clicked ${clicks} times`)
    ]))
  };
}

run(main, {
	DOM: makeDOMDriver('#app')
});
```

**Comment by voronianski** [comment]
@real34 it's again npm bug -https://github.com/npm/npm/issues/6581#issuecomment-174718361  due to this dependency https://github.com/cyclejs/cycle-dom/blob/master/package.json#L26

I've sent PR already - https://github.com/npm/npm/issues/6581#issuecomment-174718361
