### ISSUE TITLE
Dones't work on Firefox

### ISSUE THREAD

**Issue by jdinartejesus** [voronianski/esnextbin#40]
I'm having this following error on the console when running on Firefox v48. 
Doesn't render anything on the HTML view.

```error { target: IDBOpenDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, timeStamp: 1471555134046582, originalTarget: IDBOpenDBRequest, explicitOriginalTarget: IDBOpenDBRequest, NONE: 0, CAPTURING_PHASE: 1 }```

**Comment by voronianski** [comment]
fixed
