### ISSUE TITLE
Capture Cmd+[ keyboard events

### ISSUE THREAD

**Issue by gravitypersists** [voronianski/esnextbin#42]
In sublime/atom this is the default to shift the text, but in browsers it acts as a back button. When working with a saved gist, it does not automatically save so pressing these keys (out of habit) means you go back to the previous browser page and lose all of your work.

**Comment by voronianski** [comment]
@gravitypersists please provide list of keyboard shortcuts and actions that you'd like to have.

**Comment by gravitypersists** [comment]
well, ideally, you have a key map option similar to jsFiddle. 

![screen shot 2016-08-26 at 11 24 47 am](https://cloud.githubusercontent.com/assets/231863/18016155/c9149b68-6b7f-11e6-8543-f75b856c1c8b.png)

But I would just argue capturing cmd+[ for now is enough to prevent accidental navigations.

**Comment by ptim** [comment]
Thanks for esnextbin!!

I'd love a subset of Sublime shortcuts! On jsbin I'm used to using codemirror shortcuts for indentation, multi cursor, moving lines up and down...

**Comment by voronianski** [comment]
Fixed by preventing browser default behavior. 
For supported shortcuts please check - https://ace.c9.io/demo/keyboard_shortcuts.html
