### ISSUE TITLE
Error popup on bottom of text editor is intrusive

### ISSUE THREAD

**Issue by gravitypersists** [voronianski/esnextbin#43]
The errors in the text editor are intrusive when working towards the bottom of your editor.

![intrusive-error](https://cloud.githubusercontent.com/assets/231863/17986409/6bf08fba-6acf-11e6-8418-8a0f349b29bc.gif)

Some potential fixes:

 - Have a dedicated area for error messages
 - Only compile and show errors on execute

**Comment by voronianski** [comment]
@gravitypersists just scroll up - 
![esnextbin-errors](https://cloud.githubusercontent.com/assets/974035/18001024/38fe97f2-6b81-11e6-81cf-f964b317571f.gif)

**Comment by gravitypersists** [comment]
Okay. Nevermind then.
