### ISSUE TITLE
Duplicate package issue

### ISSUE THREAD

**Issue by gaearon** [voronianski/esnextbin#5]
I'm not 100% sure this is an issue with ESNextbin but I suspect so.
I'm trying to run Redux DevTools in the browser.

It displays correctly: http://esnextb.in/?gist=cf5686700affb969648e
However clicking the button has no effect.

Looking in the console, I see a warning that React prints when there are two copies of React on the page. In this case, I have both `react-dom` and `react` I imported myself, as well as `redux-devtools` and `redux-devtools-log-monitor` which depend on `react`. Is there any chance ESNextbin mistakingly downloads two copies of React rather than resolving them to a single dependency?

**Comment by voronianski** [comment]
@gaearon yes, the problem is that ESNextbin uses [Browserify-CDN](https://wzrd.in) to get bundles and (as you can see from this url -  https://wzrd.in/standalone/redux-devtools-log-monitor@latest) it will browserify module with all its' dependencies :disappointed:

**Comment by voronianski** [comment]
@gaearon I'll try to investigate now if it's could be omitted when POSTing multi.

**Comment by gaearon** [comment]
Ah, that makes sense. Thank you for investigating.

**Comment by JWo1F** [comment]
@voronianski, how to progress?

**Comment by voronianski** [comment]
@JWo1F unfortunately maintainers of http://wzrd.in do not want to proceed with this issue - https://github.com/jfhbrook/wzrd.in/issues/118

**Comment by JWo1F** [comment]
@voronianski very-very-very sadly.

**Comment by oomathias** [comment]
Hi @voronianski 

I've been working on something like http://wzrd.in, it's called https://bndl.co.
It's still in development (I'll open source it) and I hope to launch it in beta next week.

For now, you can try it like that: `https://bndl.co/react@15.0.2/redux`.
I also plan to support a `POST` method with a `package.json` and maybe others endpoints if needed.

It uses `yarn` and `browserify` behind the hood and bundles everything together without checking for missing package.

So, https://bndl.co/react/react-redux works, even though `redux` is missing.
And something like https://bndl.co/react/react-redux/react-dom/redux/redux-form works too, with only one version of each package (compared to wzrd.in which includes multiples react and redux).

_The server may be down, like I said it's not launched yet._

**Comment by voronianski** [comment]
@oomathias that's awesome! thank you very much for your work 🎉 I will try to play with it and use it instead of wzrd.i when you'll be ready.

**Comment by voronianski** [comment]
@oomathias I just noticed that https://bndl.co/ is not working, did you manage to progress with your project?
