### ISSUE TITLE
Height of editor changes incorrectly with viewport height

### ISSUE THREAD

**Issue by bogas04** [voronianski/esnextbin#6]
### What ?
I think JS is deciding the height of editor and due to latency it fails to do that correctly and results in some old height of editor. This basically : 
![screen shot 2016-02-05 at 8 20 30 pm](https://cloud.githubusercontent.com/assets/6177621/12849521/01a15432-cc46-11e5-8cc8-3104159b63fb.png)

### STR
* Write some code (full page worth of code)
* Resize browser quickly / Open inspector (docked to bottom) and close it
* Find editor height to be stuck to the previous viewport height.

### Possible fix
If you are doing viewport size calculations in JS then I would recommend you to use the viewport height dimension of CSS `height: 100vh` instead. Browsers can handle it better. 

If you aren't doing it and CSS is managing it entirely, then I don't really know what is causing this.

### System Details 
OSX with latest Firefox Nightly and on latest Chrome Canary (I tend to use latest builds).

**Comment by voronianski** [comment]
@bogas04 yeah, weird one, unfortunately related to react-ace component - https://github.com/securingsincity/react-ace/issues/82
