### ISSUE TITLE
Unable to instantiate ES6 Class

### ISSUE THREAD

**Issue by peduarte** [voronianski/esnextbin#62]
Hello!

I get the following error when I try to create an instance of an ES6 Class:
```
app.min.js?b=19082016:46 POST https://wzrd.in/multi net::ERR_INSECURE_RESPONSE
```

I've create a simple demo to illustrate the problem:
https://esnextb.in/?gist=a2476541c026211a5721cf7ce0718b5b

Note: uncomment then code then execute to replicate the error.

If I write this class as an ES5 function, and attach the methods to its prototype, it works fine.

**Comment by voronianski** [comment]
@peduarte something is wrong with https://wzrd.in/multi endpoint now. I'll investigate. Thanks!

**Comment by voronianski** [comment]
@peduarte it looks like their SSL certificate is outdated..

**Comment by peduarte** [comment]
Yeah I thought it'd be an SSL related issue. Out of curiosity, what is `wzrd.in`? If there is any way I can help to notify them about their expired SSL cert, let me know. 👍

**Comment by voronianski** [comment]
@peduarte there is an issue already - https://github.com/jfhbrook/wzrd.in/issues/147 you can upvote it as well :)

**Comment by voronianski** [comment]
@peduarte created another issue to track it separately as well - https://github.com/jfhbrook/wzrd.in/issues/148

**Comment by peduarte** [comment]
Cool will do. Thanks man!

**Comment by peduarte** [comment]
This is working now! Thanks for the super fast fix. Awesome!

**Comment by voronianski** [comment]
@peduarte awesome!
