### ISSUE TITLE
Prevent unwanted/accidental Refresh

### ISSUE THREAD

**Issue by peduarte** [voronianski/esnextbin#66]
Hello,

I've been using esnextbin quite a lot recently and I've experienced a behaviour which I found to be pretty annoying at times.

This behaviour is that, while trying to execute my code using `cmd + e` I accidentally hit `cmd + r`, which caused the page to refresh.

Refreshing the page when you have unsaved code is not an issue, as it seems the code is stored in Local Storage.

However, when you've saved your code in a gist and you accidentally press refresh without saving, it'll load the previously saved code from the gist, which makes sense!

But personally I could see the benefit of preventing this Refresh, I could see this working via an Alert box. I think the Alert box is only needed when the url contains `?gist=` query parameter, so the behaviour would remain the same for unsaved code.

What do you think about this suggestion?

**Comment by voronianski** [comment]
@peduarte thanks for your input, I really appreciate it. Confirm alert might be an issue but maybe with the feature of disabling it.

**Comment by peduarte** [comment]
@voronianski sounds reasonable!

**Comment by voronianski** [comment]
fixed by preventing refresh
