### ISSUE TITLE
Possible to set gist name dynamically?

### ISSUE THREAD

**Issue by peduarte** [voronianski/esnextbin#67]
Hello!

Is there way to set a name/description to the saved gist?

I've got quite a few gists saved now and I've noticed they're all saved with the same name and readme. I have to manually update them in order to name them, but if I ever change one of the gists, it gets overridden again.

I think it'd be a great addition to be able to set the gist name/description directly from `package.json` or `index.html meta tags` ?

What do you think about this?

**Comment by voronianski** [comment]
@peduarte yeah, can be a good feature. Maybe package.json is the best place for it.

**Comment by voronianski** [comment]
It's possible to use `description` field in package.json for this purpose now. It will save it as gist description as well.
