### ISSUE TITLE
Execution blocks the UI

### ISSUE THREAD

**Issue by bogas04** [voronianski/esnextbin#7]
While executing i.e. the pink progress bar at top is present, I can't edit my code or view anything else. I guess you can use web worker to do that part and hence not block the UI, or probably some async programming can fix it up somehow.

**Comment by voronianski** [comment]
@bogas04 actually it's a progress bar that shows overlay. Probably I will get rid of it, thanks!

**Comment by bogas04** [comment]
@voronianski Ah yeah! Makes much more sense.
