### ISSUE TITLE
Importing enzyme with react-dom fails

### ISSUE THREAD

**Issue by ptim** [voronianski/esnextbin#75]
Thanks for ESNextBin!

I'm cross posting this from https://github.com/jfhbrook/wzrd.in/issues/153 because I'm not sure where it belongs...

I'm trying to get a sketch running, and am getting a bundling error when I try to import enzyme. I understand that this is likely an issue with enzyme, and I'll go an have a look in their issues, too...

The issue is visible in the following gist if you un-comment the `import {shallow} from 'enzyme';` and the last `it()` test then click 'Execute':

- https://esnextb.in/?gist=8032ddde1be3e4d292b1e7cff6a97891
- https://gist.github.com/ptim/8032ddde1be3e4d292b1e7cff6a97891

Many thanks! ptim

```
---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: 0ee0b440-c1fe-11e6-95c3-57598f133f70 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react-dom' from '/tmp/enzyme1161114-29462-195j7a7/node_modules/enzyme/build'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/enzyme1161114-29462-195j7a7


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

**Comment by voronianski** [comment]
@ptim the problem is that enzyme relies on react-dom but is not pointing anywhere that it depends on it (line from `node_modules/enzyme/build/react-compat.js`):

```js
    // eslint-disable-next-line import/no-extraneous-dependencies
    exports.renderToStaticMarkup = renderToStaticMarkup = require('react-dom/server').renderToStaticMarkup;
```

but https://github.com/airbnb/enzyme/blob/master/package.json (no react-dom dep or peerdep).

**Comment by voronianski** [comment]
I'm not sure that wzrd.in and browserify can make something about it. Probably issue needs to raised in enzyme repo.

**Comment by ptim** [comment]
Many thanks @voronianski! I'll post an issue over at enzyme, and have a muck around with a fork as soon as I get time!
