### ISSUE TITLE
Decorators support

### ISSUE THREAD

**Issue by lukaszgrolik** [voronianski/esnextbin#76]
Currently when I try to use decorators it throws an error:
`unknown: Decorators are not supported yet in 6.x pending proposal update.`

Maybe it would be worth to use https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy?

**Comment by voronianski** [comment]
@lukaszgrolik thanks, I will take a look on it

**Comment by viko16** [comment]
Any updates? 🌚

**Comment by voronianski** [comment]
fixed
