### ISSUE TITLE
Error console window hides the code behind it

### ISSUE THREAD

**Issue by bogas04** [voronianski/esnextbin#8]
This is a very irritating bug with the UI. There's no way to hide the error console, and the editor can't be scrolled to view the code behind it, especially when the code is to the end of the window. The only way to "temporarily" hide the console is to type something blindly and then quickly fix the issue in that split second compiler takes to realize the error still exists. 

Ideally console shouldn't be "on top" of the editor, but rather stack below it. However a quick fix would be to add a close button to let user inspect the code and then fix it. 

![screen shot 2016-02-05 at 9 04 16 pm](https://cloud.githubusercontent.com/assets/6177621/12850770/68f290f0-cc4c-11e5-8fed-572c8e43f4cf.png)

**Comment by voronianski** [comment]
@bogas04 yeah, thank, already had a problem with this :+1:

**Comment by bogas04** [comment]
@voronianski :smile:  Loving the editor otherwise, especially how it seamlessly installs the modules without requiring any configuration, same for React and ES2015.
JS in 2016 really needs such editors/IDEs that cut of the need of understanding all the tools for newbies. 
Kudos for making the learning curve less steep!

**Comment by voronianski** [comment]
@bogas04 thanks a lot!
