### ISSUE TITLE
wzrd.in is down giving 502

### ISSUE THREAD

**Issue by dasnixon** [voronianski/esnextbin#83]
Was trying to use esnextbin, but as stated, getting a `502` from wzrd.in.

<img width="936" alt="screen shot 2017-01-31 at 2 56 34 pm" src="https://cloud.githubusercontent.com/assets/672057/22488193/87420e7e-e7c5-11e6-9bc6-aefa7de3cc88.png">

**Comment by richchurcher** [comment]
Confirmed, same here.

**Comment by voronianski** [comment]
@richchurcher @dasnixon yes, unfortunately :( https://github.com/jfhbrook/wzrd.in/issues/156

**Comment by voronianski** [comment]
@dasnixon @richchurcher works now!

**Comment by richchurcher** [comment]
Thanks Dmitri!
