### ISSUE TITLE
Can we use babel plugins?

### ISSUE THREAD

**Issue by bogas04** [voronianski/esnextbin#9]
I wanted to try out various [css in js](https://github.com/MicheleBertoli/css-in-js) methods on your app, and was wondering if I can try [babel-plugin-css-in-js](https://github.com/martinandert/babel-plugin-css-in-js).

If not then it would be a cool feature to add the the website, eventually !

**Comment by voronianski** [comment]
@bogas04 for now there's no way to extend current babel setup, however I'll investigate possibility to add this plugin.

**Comment by voronianski** [comment]
@bogas04 it won't be possible to `babel-plugin-css-in-js` as it produces css files.
